# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [3]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import json

# Import API key
from api_keys import g_key
print(g_key)

AIzaSyBM0RRaRHjyywig8UMc8rgUjC8laU3PRq0

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [4]:
#path to the csv file
cities_data = "C:/Users/Claudia/Documents/USC-Bootcamp/python_API/WeatherPy/city_df_output.csv"

#bring in the csv that was saved from weatherpy
cities_df = pd.read_csv(cities_data, encoding="utf-8")
cities_df

,Unnamed: 0,City,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,0,plaeng yao,13.58,101.28,90.00,78,64,7.76,TH,1590628674
1,1,esperance,-33.87,121.90,53.60,81,40,16.11,AU,1590628675
2,2,iralaya,15.00,-83.23,82.74,80,100,12.50,HN,1590628675
3,3,ushuaia,-54.80,-68.30,39.20,64,40,3.36,AR,1590628599
4,4,cabo san lucas,22.89,-109.91,84.00,60,5,12.75,MX,1590628510
...,...,...,...,...,...,...,...,...,...,...
579,579,kaputa,-8.47,29.66,67.89,72,0,2.73,ZM,1590628803
580,580,verkhoyansk,67.54,133.38,39.58,72,100,12.01,RU,1590628803
581,581,kashi,39.45,75.98,75.20,17,0,13.42,CN,1590628803
582,582,kralendijk,12.15,-68.27,82.40,78,56,14.99,BQ,1590628804
583,583,shirokiy,49.76,129.52,69.71,49,0,7.29,RU,1590628804

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [ ]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [ ]:
# Add marker layer ontop of heat map


# Display figure